### ISSUE TITLE
Reconfigure existing app for Cloudwatch logs

### ISSUE THREAD

**Issue by herder** [cloudcaptainsh/cloudcaptain#117]
Is it possible to reconfigure an app so that it uses the Cloudwatch logs?
We'd really like to be able to let our apps just log to stdout, and remove our current log appenders.

**Comment by axelfontaine** [comment]
This is definitely on our roadmap. To avoid having to wait though, we can also do this for you today if you give us the names of the apps that you want reconfigured. After the change is completed, new images will be fused with the Cloudwatch Logs agent and all stdout and stderr output will be redirected to the appropriate LogStream (auto-created if it doesn't exist) on CloudWatch Logs.

Just be aware that in order to use the CloudWatch Logs integration, you will need to update the policy of the cross-account Boxfuse IAM role to give it enough permissions to do so. You can find the updated policy document on the AWS Account tab in the Boxfuse Console, after clicking on the Change button.

**Comment by herder** [comment]
Great, good to know!
I'll create an issue for our team and get back to you if we decide that we need to switch before you have the feature officially implemented.

Thanks!

**Comment by forbode** [comment]
Great! I assume I can just delete and re-create the app as well, correct? I don't have an issue doing that since I am currently in testing.

**Comment by axelfontaine** [comment]
Correct.

**Comment by axelfontaine** [comment]
Starting with Boxfuse Client 1.24.0.1207 new applications are automatically configured for CloudWatch Logs by default, both when using the client as well as the console.

**Comment by patrizz** [comment]
+1 bumped into this issue as well today.  
In my case I could easily recreate the app. 
however, a checkbox or command line interface option to enable the logs would have been even handier :)
