### ISSUE TITLE
Ability to configure cloudwatch log agent

### ISSUE THREAD

**Issue by herder** [cloudcaptainsh/cloudcaptain#131]
We'd like to be able to configure the Cloudwatch agent to get our logs parsed correctly.

Specifically, we need to be able to specify multiline start pattern (See http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html ) 
so that stack traces and the like end up in the same log entry.

**Comment by axelfontaine** [comment]
That certainly makes sense in order to be able to deal with exception stacktraces, multineline output, ... Since these are things we probably can't reliably detect generically, an argument for the agent like `-multilineStartPattern=...` where ... is a regex as it is for the AWS Python agent is most likely the best option.

In order to make this available sooner, we would gladly accept a pull request for https://github.com/boxfuse/cloudwatchlogs-agent

In addition to this a new configuration property will be required in the Boxfuse Client to expose this. The alternative would be a special environment variable that would contain the arguments for the agent. We are still undecided on which may be better.

**Comment by axelfontaine** [comment]
@forbode Is the default Boxfuse convention (logGroup = boxfuse/envname, logStream= user/app) not working for you? If not, what do you use instead?

**Comment by forbode** [comment]
I'm prone to changing things as I evolve the team and software so it's hard
to say what our convention is. Right now your defaults suffice. It's in the
long run I could see grouping them differently. This is by no means urgent.

**Comment by jtheuer** [comment]
we would also like to customize our log group name because we don't group by the deployment technology but the stack name: `group=/my-custom-stack-name-prod/application-logs/` the stream name can be anything, e.g. `boxfuse`
